server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-github/config-repo  # Укажите свой репозиторий с конфигами
          search-paths: configs  # Папка с конфигами
          clone-on-start: true   # Клонировать репозиторий при старте